name: CI - Test, Lint, and SC2 Integration

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  SC2_PATH: ${{ github.workspace }}/StarCraftII

jobs:
  test:
    name: Run Tests
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install StarCraft II
      run: |
        # Download and extract SC2 API
        $apiUrl = 'https://github.com/Blizzard/s2client-proto/releases/download/latest/s2client-api-windows-x64.zip'
        $output = 's2client-api.zip'
        Invoke-WebRequest -Uri $apiUrl -OutFile $output
        Expand-Archive -Path $output -DestinationPath $env:SC2_PATH -Force
        
        # Set environment variable
        echo "SC2PATH=$env:SC2_PATH" | Out-File -FilePath $env:GITHUB_ENV -Append
        
        # Verify SC2 installation
        if (Test-Path "$env:SC2_PATH/Versions") {
            echo "SC2 installation verified"
        } else {
            echo "SC2 installation failed"
            exit 1
        }
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov pytest-asyncio
    
    - name: Run tests
      run: |
        python -m pytest tests/ -v --cov=src --cov-report=xml --asyncio-mode=auto
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false

  lint:
    name: Lint with flake8
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    
    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
